version: '2.1'
services:
  tomcat_eb:
    build: .
    image: site
    container_name: pashchuk-app
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      postgresql:
        condition: service_healthy


  postgresql:
    image: postgres
    container_name: pashchuk-postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

